[project]
name = "twilio_manager_backend"
version = "0.1.0"
description = "The backend for the Twilio Multi-Tenant Voice & SMS Management Platform."
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
exclude = ["tests*"]
